server:
  port: 30000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce
    username: postgres
    password: mysecretpassword

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    open-in-view: false
